#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_RIVERFLOW
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE

#define RGB_MATRIX_TIMEOUT 900000      // 900k ms is 15 minutes
#define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
